### PR TITLE
Add TTL header for standard Web Push requests

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by marco-c** [comment]
The TTL header is now required: https://github.com/webpush-wg/webpush-protocol/pull/77.

**Comment by jankeromnes** [comment]
FYI The Push demo is broken in Firefox because of that missing TTL header.

**Comment by marco-c** [comment]
@gauntface ping?

**Comment by marco-c** [comment]
@gauntface ping?

**Comment by gauntface** [comment]
Sorry missed the first ping. I want to try and get off of app engine for this demo. Will take a look tonight and see what I can get going.

**Comment by marco-c** [comment]
We also have another problem with the frontend code, `navigator.permissions.query({name: 'push', userVisibleOnly: true})` is not implemented in Firefox (it doesn't throw an exception in non-Nightly because we were using the old IDL and checking for `userVisible`). Maybe you could replace it with `Notification.permission === 'granted'`?

**Comment by gauntface** [comment]
Hi Marco-c I've removed it and just moved the whole hosting to github pages (avoids this repo being needed and simplifies things).

I've added some end to end tests to ensure things are working in chrome and firefox for basic push, encryption is next on my list. Sorry for the long delay on all this.

**Pull request closed without merging**
